#!/usr/bin/env python

""" Cumulus Cloud Tool """

import sys

try:
    import lib
except Exception as error:
    print('Configuration error: {}'.format(error))
    sys.exit(1)


if __name__ == '__main__':
    try:
        lib.main()
    except lib.exceptions.ConfigurationException as error:
        sys.exit(1)
    except lib.exceptions.HookExecutionException:
        sys.exit(1)
    except KeyboardInterrupt:
        sys.exit(0)
    except Exception:
        sys.exit(1)

    sys.exit(0)

sys.exit(1)
