#!/usr/bin/env python

""" Cumulus Deployment Suite

APACHE LICENSE 2.0
Copyright 2013-2014 Skymill Solutions

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import sys

try:
    import cumulus_ds
except Exception as error:
    print('Configuration error: {}'.format(error))
    sys.exit(1)


if __name__ == '__main__':
    try:
        cumulus_ds.main()
    except cumulus_ds.exceptions.ConfigurationException:
        sys.exit(1)
    except cumulus_ds.exceptions.HookExecutionException:
        sys.exit(1)
    except KeyboardInterrupt:
        sys.exit(0)
    except Exception:
        sys.exit(1)

    sys.exit(0)

sys.exit(1)
